### ISSUE TITLE
Extract Bookmarks.js generate* methods into separate module 

### ISSUE THREAD

**Issue by trystant** [thinkful-ei24/gabriel-bookmarks-app#7]
Looking through this code, it seems that all of the `generate*` and/or `render*` methods could be extracted to another module, using the [extract method](https://refactoring.com/catalog/extractMethod.html) refactoring pattern. 

A listing of all the methods is below:

https://github.com/thinkful-ei24/gabriel-bookmarks-app/blob/116aa46d3259c48e588bc01bad2d6be79472dfef/scripts/bookmarks.js#L196-L424

**Comment by GabrielMorris** [comment]
Generators have been extracted into their own module
